### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by zgotsch** [nwolverson/atom-ide-purescript#160]
Reproduction:
1. Restarted PSCI via "Ide Purescript: psci reset" in command palette (ctl-p).
2. PSCI tried to build my project's Main, but it was broken.
3. When sending a newline in PSCI in Atom, got "Uncaught Error: This socket has been ended by the other party".

I was unable to reset the psci after this. I was able to reset Ide Purescript entirely from the command palette (I received the success message), but continued to get the error when attempting to use psci in Atom. A full relaunch of Atom made the error stop occurring.

I suspect the IDE server crashed or errored, but the atom side should probably detect this and relaunch a new server with a new socket?

**Atom**: 1.16.0 x64
**Electron**: 1.4.16
**OS**: linux 4.10.13-1-ARCH
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package 0.17.2

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:160

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:286:12)
    at /packages/ide-purescript/lib/main.js:9036:22
    at /packages/ide-purescript/lib/main.js:1220:18
    at /packages/ide-purescript/lib/main.js:1220:22
    at __do (/packages/ide-purescript/lib/main.js:11703:246)
    at __do (/packages/ide-purescript/lib/main.js:11711:41)
    at __do (/packages/ide-purescript/lib/main.js:11852:46)
    at __do (/packages/ide-purescript/lib/main.js:11881:11)
    at /packages/ide-purescript/lib/main.js:1278:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:259:29)
    at /usr/lib/atom/src/command-registry.js:3:59
    at Object.didConfirmSelection (/usr/lib/atom/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:292:20)
    at HTMLDivElement.core:confirm (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:64:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:259:29)
    at /usr/lib/atom/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:40.4.0 intentions:highlight (input.hidden-input)
     -0:40.2.0 command-palette:toggle (input.hidden-input)
  3x -0:38.1.0 core:move-down (input.hidden-input)
     -0:36.3.0 editor:consolidate-selections (input.hidden-input)
     -0:36.3.0 core:cancel (input.hidden-input)
     -0:35.4.0 intentions:highlight (input.hidden-input)
     -0:35.2.0 command-palette:toggle (input.hidden-input)
  8x -0:32.9.0 core:move-down (input.hidden-input)
  6x -0:30.7.0 core:move-up (input.hidden-input)
  2x -0:25.8.0 core:move-down (input.hidden-input)
     -0:22.8.0 core:confirm (input.hidden-input)
     -0:22.8.0 ide-purescript:restart-psc-ide (input.hidden-input)
     -0:21.2.0 intentions:highlight (input.hidden-input)
     -0:20.9.0 command-palette:toggle (input.hidden-input)
     -0:16.9.0 core:confirm (input.hidden-input)
     -0:16.9.0 ide-purescript:psci-open (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
elm-format 2.1.0 
elmjutsu 5.5.2 
hidpi 0.12.0 
ide-purescript 0.17.2 
intentions 1.1.2 
language-babel 2.61.0 
language-elm 1.5.0 
language-haskell 1.12.1 
language-purescript 0.8.2 
language-rust 0.4.10 
linter 2.1.4 
linter-elm-make 0.23.2 
linter-pep8 1.3.2 
linter-pycodestyle 2.0.2 
linter-rust 0.8.0 
linter-ui-default 1.2.4 
```

**Comment by nwolverson** [comment]
PSCI is just actually lauched via the standard command, and will be unaffected by the IDE server restart command; I assume the process died. I guess we should make sure if the process dies, there are no remaining references and it can be restarted, make sure this can be forced too.
