### ISSUE TITLE
Failed to activate the ide-purescript package

### ISSUE THREAD

**Issue by paf31** [nwolverson/atom-ide-purescript#17]
I think this is related to having multiple projects open at the same time, but `{dir}` is clearly not defined inside the string literal.

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.3
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.4.0
### Stack Trace

Failed to activate the ide-purescript package

```
At dir is not defined

ReferenceError: dir is not defined
  at PscIde.startServer (/Users/paf31/.atom/packages/ide-purescript/lib/psc-ide.coffee:40:71)
  at PscIde.activate (/Users/paf31/.atom/packages/ide-purescript/lib/psc-ide.coffee:10:6)
  at Object.module.exports.activate (/Users/paf31/.atom/packages/ide-purescript/lib/main.coffee:39:13)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:915:28
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.triggerActivationHook (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:41)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:180:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.reloadGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:191:21)
  at new TokenizedBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:73:12)
  at new DisplayBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:69:32)
  at new TextEditor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:86:30)
  at Project.module.exports.Project.buildEditorForBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:514:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:403:24
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

**Comment by nwolverson** [comment]
Multiple projects are not supported yet (as only a single port for `psc-ide` is configured) but this definitely shouldn't be the result.

**Comment by nwolverson** [comment]
Sorry my comment was misleading, this error is shown in case you have multiple projects open in one atom window, multiple projects in multiple atom windows should be slightly different (but still not work just now).

Seems to work, thanks!
