### ISSUE TITLE
Autocomplete throws error

### ISSUE THREAD

**Issue by MonoidMusician** [nwolverson/atom-ide-purescript#184]
Autocomplete has been failing with this error for me:
```
Uncaught (in promise) Error: Request workspace/executeCommand failed with message: Cannot read property 'version' of undefined
    at new ResponseError (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/messages.js:46)
    at handleResponse (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:430)
    at processMessageQueue (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:258)
    at Immediate.<anonymous> (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:242)
    at runCallback (timers.js:651)
    at tryOnImmediate (timers.js:624)
    at processImmediate [as _immediateCallback] (timers.js:596)
```
with `atom-ide-ui` 0.7.2, PS 0.11.7, and this package at 0.21.0

**Comment by MonoidMusician** [comment]
Other error from trying to run a build:
```
Error: Connection is disposed.
    at new ConnectionError (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:616:19)
    at Object.sendRequest (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:715:13)
    at LanguageClientConnection._sendRequest (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/@nwolverson/atom-languageclient/build/lib/languageclient.js:386:34)
    at LanguageClientConnection.executeCommand (/Users/monoidmusician/.atom/packages/ide-purescript/node_modules/@nwolverson/atom-languageclient/build/lib/languageclient.js:353:17)
    at exports.executeCommandImpl (/Users/monoidmusician/.atom/packages/ide-purescript/lib/main.js:6164:23)
    at /Users/monoidmusician/.atom/packages/ide-purescript/lib/main.js:1143:18
    at /Users/monoidmusician/.atom/packages/ide-purescript/lib/main.js:3464:18
    at /Users/monoidmusician/.atom/packages/ide-purescript/lib/main.js:3381:19
    at /Users/monoidmusician/.atom/packages/ide-purescript/lib/main.js:3428:22
    at /Users/monoidmusician/.atom/packages/ide-purescript/lib/main.js:1052:18
    at /Users/monoidmusician/.atom/packages/ide-purescript/lib/main.js:1052:22
    at HTMLElement. (/Users/monoidmusician/.atom/packages/ide-purescript/lib/main.js:1121:19)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```
(This is one of those errors that has the nice little red popup)

Thanks for offering to take a look!

**Comment by nwolverson** [comment]
I can't repro with those versions. It would be interesting to see some more info, in particular I think the language server process seems to have died.

1. Is it (a) happening 100% of the time (b) happening occasionally or (c) at some point it goes wrong then stays broken - I'm suspecting either (c) or (a)?
2. When this has happened can you check the running processes for the language server - I see
`/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper /Users/nicholaw/.atom/packages/ide-purescript/node_modules/purescript-language-server/server.js --stdio` - and for the `purs ide server`
3. Can you try in the dev console, running `atom.config.set('core.debugLSP', true)` - and retry (from freshly reloaded window),

**Comment by MonoidMusician** [comment]
So it seemed to be consistently happening only in my one project, then I fussed around with things and restarted Atom multiple times, and it started working again ... and I reverted the changes I made but it still seems to be working, so I don't know what's up!

1. Consistently in one project, until it went away, so ... (a)?
2. I get an error when I try to do that:
```
$ /Applications/Atom.app/Contents/Frameworks/Atom\ Helper.app/Contents/MacOS/Atom\ Helper /Users/monoidmusician/.atom/packages/ide-purescript/node_modules/purescript-language-server/server.js --stdio
module.js:472
    throw err;
    ^

Error: Cannot find module '/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/Resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:424:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:544:3
```
3. I didn't see any noteworthy information when I did that, but I don't know what I'm looking for. In particular, the `purescript.addCompletionImport` command seemed to be configured the same each time but now it doesn't throw an error ...

I'll let you know if it comes up again, but doesn't seem to be an issue right now.

**Comment by MonoidMusician** [comment]
Yeah I haven't run into issues with this again, it seems to be working well!

**Comment by maackle** [comment]
I run into this every once in a while too, and I haven't found any pattern as to why it happens. This time I was getting the error when attempting to Build.
