### ISSUE TITLE
Manual installation of language-purescript & atom-ide-ui necessary

### ISSUE THREAD

**Issue by cemerick** [nwolverson/atom-ide-purescript#194]
The README says that these plugins will be installed automatically upon opening the first purescript file, but I found I had to install them manually. Until I did so, I got `TypeError: Cannot read property 'executeCommand' of null` errors upon trying to start the IDE server.

**Comment by nwolverson** [comment]
So you visited a PureScript file, and nothing much happened, then you tried to start the IDE server yourself? Or this happened when the plugin tried to start it for you?

I don't think installation of package deps in this package has changed for a very long time, but it's possible something else in the ecosystem has which has broken this.

**Comment by cemerick** [comment]
Correct, _nothing_ happened when I visited a PS file, and the error popped when I attempted to start the server explicitly from the package menu.

**Comment by Jovonni** [comment]
+1

**Comment by Jovonni** [comment]
Upon attempting to "build":

TypeError: Cannot read property 'executeCommand' of null at exports.executeCommandImpl (/Users/jovonnipharr/.atom/packages/ide-purescript/lib/main.js:6187:23) at /Users/jovonnipharr/.atom/packages/ide-purescript/lib/main.js:1143:18 at /Users/jovonnipharr/.atom/packages/ide-purescript/lib/main.js:3464:18 at /Users/jovonnipharr/.atom/packages/ide-purescript/lib/main.js:3381:19 at /Users/jovonnipharr/.atom/packages/ide-purescript/lib/main.js:3428:22 at /Users/jovonnipharr/.atom/packages/ide-purescript/lib/main.js:1052:18 at /Users/jovonnipharr/.atom/packages/ide-purescript/lib/main.js:1052:22 at /Users/jovonnipharr/.atom/packages/ide-purescript/lib/main.js:1121:19 at

**Comment by Jovonni** [comment]
had to switch to the "Language Purescript" package :(

**Comment by winston0410** [comment]
Having the same issue here!

TypeError: Cannot read property 'executeCommand' of null at exports.executeCommandImpl (/Users/hugosum/.atom/packages/ide-purescript/lib/main.js:6187:23) at /Users/hugosum/.atom/packages/ide-purescript/lib/main.js:1143:18 at /Users/hugosum/.atom/packages/ide-purescript/lib/main.js:3464:18 at
