### ISSUE TITLE
Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

### ISSUE THREAD

**Issue by jutaro** [nwolverson/atom-ide-purescript#34]
Please can you fix this for Atom 1.1. I realised as well that jumping to errors does not work for newest psc. Best regards and thanks. Jürgen

**Atom Version**: 1.1.0
**System**: Ubuntu 15.10
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.6.1
### Stack Trace

Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

```
At /home/jutaro/.atom/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:53

TypeError: editor.displayBuffer.getScrollTop is not a function
  at showExpressionType (/home/jutaro/.atom/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:53:49)
  at /home/jutaro/.atom/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:40:63

```
### Commands

```
     -0:37.1.0 tabs:close-all-tabs (div.title)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "projectHome": "/home/jutaro/Develop"
  },
  "ide-purescript": {
    "pscIdeExe": "/home/jutaro/Develop/cabal-unpack/psc-ide/.cabal-sandbox/bin/psc-ide",
    "pscIdeServerExe": "/home/jutaro/Develop/cabal-unpack/psc-ide/.cabal-sandbox/bin/psc-ide-server",
    "enableAtomLinter": false
  }
}
```
### Installed Packages

``` coffee
# User
build, v0.48.0
file-icons, v1.6.11
haskell-ghc-mod, v1.1.1
ide-haskell-cabal, v1.0.0
ide-purescript, v0.6.1
language-haskell, v1.4.12
language-purescript, v0.4.0
linter, v1.9.1
linter-hlint, v0.4.2
minimap, v4.15.0
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by nwolverson** [comment]
Thanks, I have not updated to 1.1 yet. Will hopefully take a look at this tonight.

**Comment by nwolverson** [comment]
Fixed in local `hover-tooltips` revision.
