### ISSUE TITLE
deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by mrmurphy** [nwolverson/atom-ide-purescript#36]
Hi, there! Just trying to get this plugin working, and I get this error whenever I open a .purs file

**Atom Version**: 1.2.1
**System**: Mac OS X 10.11.1
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.7.1
### Stack Trace

Failed to activate the ide-purescript package

```
At deprecationSite.getFileName is not a function

TypeError: deprecationSite.getFileName is not a function
  at Object.global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
  at Object.defineProperty.get [as TextEditor] (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:38:14)
  at Object.<anonymous> (/Users/murphy/.atom/packages/ide-purescript/lib/editors.coffee:1:35)
  at Object.<anonymous> (/Users/murphy/.atom/packages/ide-purescript/lib/editors.coffee:1:1)
  at Module._compile (module.js:434:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/murphy/.atom/packages/ide-purescript/lib/main.coffee:5:11)
  at Object.<anonymous> (/Users/murphy/.atom/packages/ide-purescript/lib/main.coffee:1:1)
  at Module._compile (module.js:434:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:14)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:166:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:784:28
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at PackageManager.module.exports.PackageManager.triggerActivationHook (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:528:41)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:181:27)
  at TokenizedBuffer.module.exports.TokenizedBuffer.reloadGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:192:21)
  at new TokenizedBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:78:12)
  at new DisplayBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:85:32)
  at new TextEditor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:120:30)
  at Workspace.module.exports.Workspace.buildTextEditor (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:570:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:550:24
  at process._tickCallback (node.js:368:9)

```
### Commands

```
     -1:05.9.0 tree-view:toggle (atom-pane.pane.active)
  3x -1:02.3.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:56.6.0 project-viewer:toggle (atom-text-editor.editor.is-focused)
     -0:51.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:47.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-material-ui)
     -0:06.7.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "nuclide-click-to-symbol",
      "jsformat",
      "nuclide-format-js"
    ],
    "customFileTypes": {
      "source.css": [
        "icss",
        "istyl"
      ],
      "source": [
        "[object Object]"
      ]
    },
    "projectHome": "/Users/murphy/projects",
    "themes": [
      "atom-material-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
atom-material-ui, v0.8.0
autocomplete-paths, v1.0.2
cursor-history, v0.5.9
emmet, v2.3.14
ide-purescript, v0.7.1
javascript-snippets, v1.0.0
language-elm, v1.3.0
language-haskell, v1.5.0
language-purescript, v0.4.0
linter, v1.11.2
minimap, v4.16.0
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-selection, v4.3.1
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-flow, v0.0.32
nuclide-type-hint, v0.0.32
pigments, v0.18.1
pretty-json, v0.4.1
project-viewer, v0.2.19
react, v0.12.10
seti-syntax, v0.4.1
statusbar-datetime, v0.9.7
vim-mode-plus, v0.3.0

# Dev
No dev packages
```

**Comment by nwolverson** [comment]
Thanks! In common with other packages, seems to be atom upgrade breakage. Will take a look this evening.

**Comment by nwolverson** [comment]
Actually think this is to do with nuclide https://github.com/atom/atom/issues/9350 https://github.com/facebook/nuclide/issues/246 https://github.com/atom/atom/issues/9641 - may be worth trying with those packages disabled.

**Comment by mrmurphy** [comment]
You are correct! Disabling Nuclide solves the problem. Thanks!
