### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by adkelley** [nwolverson/atom-ide-purescript#39]
From my terminal:
pulp init
atom .

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.7.1
### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/Gibson/.atom/packages/ide-purescript/lib/psc-ide.coffee:39:16
    at PscIde.runCmd (/Users/Gibson/.atom/packages/ide-purescript/lib/psc-ide.coffee:21:16)
    at PscIde.getWorkingDir (/Users/Gibson/.atom/packages/ide-purescript/lib/psc-ide.coffee:91:6)
    at PscIde.startServer (/Users/Gibson/.atom/packages/ide-purescript/lib/psc-ide.coffee:64:6)
    at PscIde.activate (/Users/Gibson/.atom/packages/ide-purescript/lib/psc-ide.coffee:13:6)
    at Object.module.exports.activate (/Users/Gibson/.atom/packages/ide-purescript/lib/main.coffee:46:13)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:847:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:547:36)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:487:17
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "ide-purescript": {
    "pscIdeExe": "/usr/local/bin",
    "pscIdeServerExe": "/usr/local/bin"
  }
}
```
### Installed Packages

``` coffee
# User
ide-purescript, v0.7.1
language-elm, v1.3.2
language-purescript, v0.6.1

# Dev
No dev packages
```

**Comment by nwolverson** [comment]
Ah, the psc-ide executable config wants the full path not the containing directory. So 
`"pscIdeExe": "/usr/local/bin/psc-ide"`

**Comment by adkelley** [comment]
Thank you.  Now that’s settled onto the next bug.  Any special consideration for the server port?  The server won’t start,
and its asking me to check the configuration (see attached).  Finally, how do I actually run the build command?

Cheers,
Alex

**Comment by nwolverson** [comment]
I don't think you can include attachments in replies to github issues. The server port should default to `4242` (also the `psc-ide-server` default), by default if you let the plugin start the server process for you it should just work assuming the port is available. You could try running `psc-ide-server --debug` by hand to see if you get any information there. Also the assumption is you are running this with a "project" open - i.e. atom is opened at a folder with 'src' folder at the root containing purescript files etc.

Build is either via linter - just on save, assuming you installed the linter plugin; or via the build plugin, assuming you installed that - see https://github.com/nwolverson/atom-ide-purescript#build
I plan on releasing a new version which changes this up once psc version 8.0 is released. Also more documentation it seems :)

**Comment by adkelley** [comment]
Thank you Nicolas.  I really appreciate your help.  I was able to get the server running standalone with debugging.  I haven’t installed the linter plugin, so I’ll try that as well.  Thanks again!

Cheers,
Alex

**Comment by adkelley** [comment]
Hi Nicholas,
I’m pleased to mention its all working now.  I just recently started using Atom (coming from Emacs) and didn’t realize that build and linter needed to be installed separately.  All is well.  Thank you again for your support.

Cheers,
Alex

**Comment by nwolverson** [comment]
Unfortunately atom still doesn't allow package dependencies, at least natively. Glad you got it working.
