### ISSUE TITLE
psci won't start

### ISSUE THREAD

**Issue by jchayat** [nwolverson/atom-ide-purescript#43]
[Enter steps to reproduce below:]
1. use psci open command

**Atom Version**: 1.4.2
**System**: Mac OS X 10.10.5
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.8.1
### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
    at Socket._writeGeneric (net.js:640:19)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at PsciProcess.kill (/Users/jon/.atom/packages/ide-purescript/lib/psci.coffee:13:17)
    at Psci.killProc (/Users/jon/.atom/packages/ide-purescript/lib/psci.coffee:56:11)
    at Psci.startPsci (/Users/jon/.atom/packages/ide-purescript/lib/psci.coffee:69:6)
    at Psci.startPsci (/Users/jon/.atom/packages/ide-purescript/lib/psci.coffee:1:1)
    at Psci.openPsciCommand (/Users/jon/.atom/packages/ide-purescript/lib/psci.coffee:66:6)
    at atom-workspace.<anonymous> (/Users/jon/.atom/packages/ide-purescript/lib/psci.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:16.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:12.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.7.0 psci:open (atom-text-editor.editor)
     -0:06.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 psci:open (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
ide-purescript, v0.8.1
language-elm, v1.3.0
language-purescript, v0.6.1

# Dev
No dev packages
```

**Comment by nwolverson** [comment]
Hmm, this is still working for me with the same atom and ide-purescript versions, also on OSX. What version of pulp and psci do you have, and is the psci via npm or direct?

Is this error from a 2nd/more attempt or the first time opened? Looks like it's failing to kill an old psci.

**Comment by nwolverson** [comment]
Wrong issue link.

**Comment by jchayat** [comment]
ps was installed using brew. I uninstalled and reinstalled latest using npm. pulp also upgraded to latest.

Problem still exists.

**Comment by nwolverson** [comment]
So hopefully this is no longer an issue, at least everything is different.

**Comment by nwolverson** [comment]
Closing this as the code has been entirely rewritten and certainly the crash above cannot possibly occur. Of course there may still be other issues.
