### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lintOnBuild' of undefined

### ISSUE THREAD

**Issue by CRogers** [nwolverson/atom-ide-purescript#45]
[Enter steps to reproduce below:]
1. Run "Purescript: Build"

**Atom Version**: 1.4.3
**System**: Mac OS X 10.10.5
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.8.2
### Stack Trace

Uncaught TypeError: Cannot read property 'lintOnBuild' of undefined

```
At /Users/callumr/.atom/packages/ide-purescript/lib/main.coffee:85

TypeError: Cannot read property 'lintOnBuild' of undefined
    at Main.lint (/Users/callumr/.atom/packages/ide-purescript/lib/main.coffee:85:14)
    at atom-workspace.<anonymous> (/Users/callumr/.atom/packages/ide-purescript/lib/main.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  5x -1:24.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:18.3.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:13.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:12.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  7x -0:04.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 purescript:build (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "stack-ide-atom",
      "haskell-ghc-mod"
    ]
  },
  "ide-purescript": {}
}
```
### Installed Packages

``` coffee
# User
ide-purescript, v0.8.2
indent-guide-improved, v1.4.5
language-docker, v1.1.3
language-gradle, v0.0.3
language-haskell, v1.5.0
language-purescript, v0.6.1
language-restructuredtext, v0.9.0
minimap, v4.16.0
tidy-tabs, v0.3.0

# Dev
No dev packages
```

**Comment by nwolverson** [comment]
You need to install https://github.com/atom-community/linter for build support. Admittedly a proper error message should have been shown.

I do plan to use https://www.npmjs.com/package/atom-package-dependencies to automatically depend on this in future, sucks that atom doesn't natively support package dependencies.

**Comment by nwolverson** [comment]
Closing due to lack of followup - please reopen if this is not the issue. Opened #50 around automating these dependencies.
