### ISSUE TITLE
Uncaught TypeError: Cannot read property 'screenPositionForMouseEvent' of null

### ISSUE THREAD

**Issue by doivosevic** [nwolverson/atom-ide-purescript#68]
[Enter steps to reproduce below:]
1. Happens when deleting an open file. I can reproduce this every time I do it. It doesn't have to be in a purescript project nor the first project on the list. The file does not have to be a purescript file.

**Atom Version**: 1.7.0-beta5
**System**: Microsoft Windows 10 Education
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.10.0
### Stack Trace

Uncaught TypeError: Cannot read property 'screenPositionForMouseEvent' of null

```
At C:\Users\Dito\.atom\packages\ide-purescript\node_modules\hover-tooltips\lib\hover-tooltips.js:100

TypeError: Cannot read property 'screenPositionForMouseEvent' of null
    at bufferPositionForMouseEvent (C:\Users\Dito\.atom\packages\ide-purescript\node_modules\hover-tooltips\lib\hover-tooltips.js:100:45)
    at showExpressionType (C:\Users\Dito\.atom\packages\ide-purescript\node_modules\hover-tooltips\lib\hover-tooltips.js:49:28)
    at C:\Users\Dito\.atom\packages\ide-purescript\node_modules\hover-tooltips\lib\hover-tooltips.js:37:63
```
### Commands

```
     -2:14.5.0 linter:lint (atom-text-editor.editor.is-focused)
     -1:55.4.0 tree-view:remove (span.name.icon.icon-file-text)
     -1:53.5.0 linter:lint (atom-text-editor.editor)
     -1:51.8.0 settings-view:open (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -1:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.9.0 linter:lint (atom-text-editor.editor)
     -0:41.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:41.4.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:15.9.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:13.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:05.1.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:03.4.0 linter:lint (atom-text-editor.editor)
     -0:01.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.2.0 linter:lint (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.asm.x86_64": [
        "*.s"
      ],
      "x86 and x86_64 Assembyl": [
        "*.s"
      ]
    },
    "disabledPackages": [
      "linter-clang"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "ide-purescript": {}
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
atom-typescript, v8.5.0
file-types, v0.5.1
fold-search-results, v1.0.5
gist-it, v0.9.1
ide-haskell-cabal, v1.2.0
ide-purescript, v0.10.0
keyboard-localization, v1.4.18
language-batch, v0.3.3
language-haskell, v1.7.9
language-purescript, v0.7.0
language-x86-64-assembly, v2.1.10
linter, v1.11.4
linter-gcc, v0.6.9
minimap, v4.21.0

# Dev
No dev packages
```

**Comment by nwolverson** [comment]
Looks like we need to update for Atom 1.7.

**Comment by nwolverson** [comment]
Actually I was wrong, this is an existing issue to do with hover-tooltips. Probably some timer going off, can either look to fix there or possibly see about stealing ide-haskells rather nice tooltips, they look pretty good now.

**Comment by kritzcreek** [comment]
steal all the things 😈

**Comment by develop7** [comment]
> this is an existing issue to do with hover-tooltips

@nwolverson has it been reported yet? If so, could you link to it?

**Comment by nwolverson** [comment]
I don't think so, probably I was going to try and reproduce. It doesn't happen often but I still see this.

**Comment by safareli** [comment]
I just had this same error (atom said that it has already been reported and i came here)

**Comment by safareli** [comment]
[Enter steps to reproduce:]

I got same error again, I just performed command click on some function.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package 0.15.3


### Stack Trace

Uncaught TypeError: Cannot read property 'screenPositionForMouseEvent' of null

```
At /Users/safareli/.atom/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:100

TypeError: Cannot read property 'screenPositionForMouseEvent' of null
    at bufferPositionForMouseEvent (/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:100:45)
    at showExpressionType (/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:49:28)
    at /packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:37:63
```

### Commands

```
  2x -8:00.5.0 core:copy (input.hidden-input)
  2x -1:23.4.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -0:49.3.0 core:close (a.btn-issue.btn.btn-error)
  2x -0:43.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -0:37.5.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
duplicate-line-or-selection 0.9.0 
editorconfig 2.2.2 
hyperclick 0.0.40 
ide-purescript 0.15.3 
intentions 1.1.2 
jumpy 3.1.3 
language-javascript-jsx 0.3.7 
language-purescript 0.8.2 
linter 2.1.0 
linter-ui-default 1.2.1 
monokai 0.22.0 
```

**Comment by nwolverson** [comment]
This was a hover-tooltips issue, no longer used.
